"""Create profession and work_activity tables

Revision ID: 1de36e99c394
Revises: 46c3c7407d89
Create Date: 2024-10-30 23:30:06.667618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1de36e99c394'
down_revision: Union[str, None] = '46c3c7407d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    profession = op.create_table('profession',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('work_activity',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('profession_id', sa.Integer(), nullable=False),
                    sa.Column('group_user_id', sa.Integer(), nullable=False),
                    sa.Column('income', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['group_user_id'], ['group_user.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_work_activity_group_user_id'), 'work_activity', ['group_user_id'], unique=False)

    professions = [
        {'name': 'Кассира 🏪'},
        {'name': 'Учителя 🏫'},
        {'name': 'Врача 👨‍⚕️'},
        {'name': 'Клоуна 🤡'},
        {'name': 'Смотрителя в тюрьме 👮‍♂️'},
        {'name': 'Повара 🧑‍🍳'},
        {'name': 'Писателя в государственном СМИ 🖊'},
        {'name': 'Диспетчера скорой помощи 🚑'},
        {'name': 'Охранника кладбища 🪦'},
        {'name': 'Режиссера мелодрам 🎬'},
        {'name': 'Безработного 🦥'},
        {'name': 'Мойщика посуды 🍽'},
        {'name': 'Художника 👩‍🎨'},
        {'name': 'Фотографа 📷'},
        {'name': 'Ведущего мероприятий 🎤'},
        {'name': 'Дворника 🧹'},
        {'name': 'Стоматолога 🦷'},
        {'name': 'Бухгалтера 💳'},
        {'name': 'Ветеринара 🐕'}
    ]
    op.bulk_insert(profession, professions)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_activity_group_user_id'), table_name='work_activity')
    op.drop_table('work_activity')
    op.drop_table('profession')
    # ### end Alembic commands ###
