"""Create profession and work_activity tables

Revision ID: 1de36e99c394
Revises: 46c3c7407d89
Create Date: 2024-10-30 23:30:06.667618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1de36e99c394'
down_revision: Union[str, None] = '46c3c7407d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    profession = op.create_table(
        'profession',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('money_max', sa.Integer(), nullable=False),
        sa.Column('money_min', sa.Integer(), nullable=False),
        sa.Column('accompanying_text', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_activity',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('profession_id', sa.Integer(), nullable=False),
                    sa.Column('group_user_id', sa.Integer(), nullable=False),
                    sa.Column('income', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['group_user_id'], ['group_user.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_work_activity_group_user_id'), 'work_activity', ['group_user_id'], unique=False)

    professions = [
        {
            'name': 'Кассира 🏪', 'money_max': 10, 'money_min': 3,
            'accompanying_text': 'Поздравляю! Твой диплом о высшем образовании был получен не зря — тебя ждет '
                                 'увлекательная смена в Пятерочке.'
        },
        {
            'name': 'Учителя 🏫', 'money_max': 21, 'money_min': 12,
            'accompanying_text': 'А после семи уроков с неуправляемыми детьми ждем тебя в психоневрологическом '
                                 'диспансере!'
        },
        {
            'name': 'Врача 👨‍⚕️', 'money_max': 22, 'money_min': 13,
            'accompanying_text': 'Твоя мечта быть проктологом-венерологом, наконец, исполнилась.'
        },
        {
            'name': 'Клоуна 🤡', 'money_max': 18, 'money_min': 10,
            'accompanying_text': 'Тебе даже стараться не надо. Быть клоуном — твое призвание.  Кстати, '
                                 'это единственное, что у тебя отлично получается.'
        },
        {
            'name': 'Смотрителя в тюрьме 👮‍♂️', 'money_max': 17, 'money_min': 11,
            'accompanying_text': 'Никто не знает, чем именно занимается смотритель в тюрьме. Поэтому ты будешь '
                                 'смотреть сериальчики.'
        },
        {
            'name': 'Повара 🧑‍🍳', 'money_max': 20, 'money_min': 10,
            'accompanying_text': 'Заранее выражаем соболезнования всем, кто попробует твою еду.'
        },
        {
            'name': 'Писателя в государственном СМИ 🖊', 'money_max': 22, 'money_min': 15,
            'accompanying_text': 'Зачисление: от Кремль, 15 рублей. Баланс: 30 рублей.'
        },
        {
            'name': 'Диспетчера скорой помощи 🚑', 'money_max': 15, 'money_min': 7,
            'accompanying_text': 'Примешь срочный вызов на "вскрыла вены, лежит, умирает и хамит".'
        },
        {
            'name': 'Охранника кладбища 🪦', 'money_max': 10, 'money_min': 1,
            'accompanying_text': 'Полиция все еще расследует загадочное исчезновение прошлого охранника. На всякий '
                                 'случай, захвати с собой распятия и святую воду.'
        },
        {
            'name': 'Режиссера мелодрам 🎬', 'money_max': 25, 'money_min': 20,
            'accompanying_text': 'Как хорошо, что никто больше не смотрит телевизор, потому что твои мелодрамы — говно.'
        },
        {
            'name': 'Безработного 🦥', 'money_max': 0, 'money_min': 0,
            'accompanying_text': 'Нищий, зато счастливый!'
        },
        {
            'name': 'Мойщика посуды 🍽', 'money_max': 10, 'money_min': 1,
            'accompanying_text': 'Самая бесполезная профессия в век посудомоечных машин. Тебе подходит, ведь ты тоже '
                                 'бесполезный.'
        },
        {
            'name': 'Художника 👩‍🎨', 'money_max': 24, 'money_min': 18,
            'accompanying_text': 'Твой максимум в творчестве — это нарисовать хуй.'
        },
        {
            'name': 'Фотографа 📷', 'money_max': 24, 'money_min': 18,
            'accompanying_text': 'Не двигайся, фоткаю клоуна.'
        },
        {
            'name': 'Ведущего мероприятий 🎤', 'money_max': 25, 'money_min': 20,
            'accompanying_text': 'Сегодня ведешь собачью свадьбу, поэтому не забудь пакетики для какашек.'
        },
        {
            'name': 'Дворника 🧹', 'money_max': 10, 'money_min': 1,
            'accompanying_text': 'Зато не с людьми и всегда на свежем воздухе.'
        },
        {
            'name': 'Стоматолога 🦷', 'money_max': 25, 'money_min': 18,
            'accompanying_text': 'День работаешь — месяц отдыхаешь на Мальдивах.'
        },
        {
            'name': 'Бухгалтера 💳', 'money_max': 23, 'money_min': 16,
            'accompanying_text': 'Опять перепутаешь пупу и лупу.'
        },
        {
            'name': 'Ветеринара 🐕', 'money_max': 24, 'money_min': 18,
            'accompanying_text': 'Будешь лечить собачек и кошечек — они будут очень рады.'
        },
        {
            'name': 'Директора цирка 🎪', 'money_max': 25, 'money_min': 20,
            'accompanying_text': 'Поздравляю! Сегодня ты директор этого чата. За это тебе полагается — ничего!'
        },
        {
            'name': 'Охотника на приведений 👻', 'money_max': 22, 'money_min': 15,
            'accompanying_text': 'Будешь вытягивать карты Таро в шкафу. Призраком окажется Деоген. Помянем!'
        },
        {
            'name': 'Пожарного👩‍🚒', 'money_max': 23, 'money_min': 14,
            'accompanying_text': 'Пожаришь картошечки.'
        },
        {
            'name': 'Швеи 🧵', 'money_max': 15, 'money_min': 8,
            'accompanying_text': 'Уколешься об веретено, проспишь всю жизнь, так и не дождавшись принца, который '
                                 'снимет с тебя проклятие.'
        },
        {
            'name': 'Фермера 🐖', 'money_max': 15, 'money_min': 6,
            'accompanying_text': 'Наконец-то исполнишь мечту и уедешь жить в деревню. Заведешь курочек, коров, '
                                 'коз и свиней.'
        },
        {
            'name': 'Садовника 🪴', 'money_max': 13, 'money_min': 5,
            'accompanying_text': 'Окажешься убийцей в очередной детективной книжке.'
        },
        {
            'name': 'Диетолога 🥒', 'money_max': 17, 'money_min': 10,
            'accompanying_text': 'Никто не пользуется услугами диетолога. Осознаешь свою бесполезность в этом мире и '
                                 'умрешь от одиночества.'
        },
        {
            'name': 'Футболиста ⚽️', 'money_max': 25, 'money_min': 23,
            'accompanying_text': 'Не забудь включить актерское мастерство и трагично упасть на поле.'
        },
        {
            'name': 'Строителя 🛠', 'money_max': 23, 'money_min': 18,
            'accompanying_text': 'Опять будешь строить из себя хуй пойми кого.'
        },
        {
            'name': 'Гадалки🔮', 'money_max': 23, 'money_min': 16,
            'accompanying_text': 'Сегодня нагадаешь порчу на понос. Себе.'
        },
        {
            'name': 'Сотрудника ритуальных услуг ⚰️', 'money_max': 24, 'money_min': 17,
            'accompanying_text': 'Хорошие клиенты — это мертвые клиенты'
        },
        {
            'name': 'Капитана корабля🚢', 'money_max': 25, 'money_min': 16,
            'accompanying_text': 'Плыви нахуй.'
        },
        {
            'name': 'Бомжа 👑', 'money_max': 25, 'money_min': 0,
            'accompanying_text': 'Наконец-то нашлась работа под твои навыки, так держать!'
        },
    ]
    op.bulk_insert(profession, professions)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_activity_group_user_id'), table_name='work_activity')
    op.drop_table('work_activity')
    op.drop_table('profession')
    # ### end Alembic commands ###
