"""First commit

Revision ID: 2b28ec70d3da
Revises: 
Create Date: 2024-10-29 23:49:51.820190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2b28ec70d3da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_chat',
                    sa.Column('chat_id', sa.BigInteger(), nullable=False),
                    sa.Column('answer_chance', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('chat_id')
                    )
    op.create_table('user',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('rank', sa.Enum('USER', 'VIP', 'PREMIUM', name='rank'), nullable=False),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('group_user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
                    sa.Column('chat_member_status',
                              sa.Enum('OWNER', 'ADMINISTRATOR', 'MEMBER', 'RESTRICTED', 'LEFT', 'BANNED',
                                      name='chatmemberstatus'), nullable=False),
                    sa.Column('money', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['telegram_chat_id'], ['telegram_chat.chat_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_group_user_telegram_chat_id'), 'group_user', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_group_user_user_id'), 'group_user', ['user_id'], unique=False)
    op.create_table('message',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('group_user_id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['group_user_id'], ['group_user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_message_group_user_id'), 'message', ['group_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_group_user_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_group_user_user_id'), table_name='group_user')
    op.drop_index(op.f('ix_group_user_telegram_chat_id'), table_name='group_user')
    op.drop_table('group_user')
    op.drop_table('user')
    op.drop_table('telegram_chat')
    op.execute('DROP TYPE rank')
    op.execute('DROP TYPE chatmemberstatus')
    # ### end Alembic commands ###
